#!/usr/bin/env python
import sys

USAGE = "Usage: pixmap <file>"

if len(sys.argv) != 2:
	print(USAGE, file=sys.stderr)
	exit(1)

file = open(sys.argv[1])

# ansii codes
mappings = {
	'a': "30",
	'b': "31",
	'c': "32",
	'd': "33",
	'e': "34",
	'f': "35",
	'g': "36",
	'h': "37",
	'A': "90",
	'B': "91",
	'C': "92",
	'D': "93",
	'E': "94",
	'F': "95",
	'G': "96",
	'H': "97",
}

for char in file.read():
	if char in mappings:
		print(f"\x1b[{mappings[char]}m█\x1b[0m", end='')
	elif char == ' ':
		print(" ",end='')
	elif char == '\n':
		print("\n", end='')

file.close()

